Repository: plone.restapi


Branch: refs/heads/7.x.x
Date: 2021-09-02T08:03:32+02:00
Author: Wesley Barroso Lopes (wesleybl) <wesleybl@gmail.com>
Commit: https://github.com/plone/plone.restapi/commit/9ee759961cbbe57114075a0c44afdd84ffcc157a

Fix tests that involving dates in Python 3.8 on machines that don't use (#1195) (#1213)

TZ = UTC

In Python 3.8, for the TZ environment variable to be recognized, you
need to call time.tzset()

Ref: https://github.com/plone/buildout.coredev/pull/701

Files changed:
M base.cfg

b"diff --git a/base.cfg b/base.cfg\nindex cce28c3da..a27ef1d70 100644\n--- a/base.cfg\n+++ b/base.cfg\n@@ -66,6 +66,10 @@ recipe = zc.recipe.testrunner\n eggs = ${instance:eggs}\n initialization =\n     os.environ['TZ'] = 'UTC'\n+    # In Python 3.8+, for the TZ environment variable to be used, it's \n+    # necessary to explicitly call time.tzset().\n+    import time\n+    time.tzset()\n     os.environ['ZSERVER_PORT'] = '55001'\n defaults = ['-s', 'plone.restapi', '--auto-color', '--auto-progress']\n \n"

